# Generated by Django 5.2.7 on 2026-01-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='_address',
            field=models.TextField(blank=True, db_column='address', null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='_phone',
            field=models.TextField(blank=True, db_column='phone', null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='industry',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('finance', 'Finance'), ('manufacturing', 'Manufacturing'), ('education', 'Education'), ('services', 'Services'), ('other', 'Lainnya')], max_length=30),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='_address',
            field=models.TextField(blank=True, db_column='address', null=True),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='_phone',
            field=models.TextField(blank=True, db_column='phone', null=True),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='education',
            field=models.CharField(blank=True, choices=[('SMA', 'SMA'), ('D3', 'D3'), ('S1', 'S1'), ('S2', 'S2'), ('other', 'Lainnya')], max_length=20),
        ),
    ]
